"""Lakebase (Postgres) access via a psycopg connection pool.

Each new pooled connection mints a fresh OAuth token as its password, so tokens
never go stale (no background refresh needed). `max_lifetime` recycles
connections before the ~1-hour token expiry. Rows come back as dicts;
Postgres `text[]` columns map to native Python lists. A tiny TTL cache keeps
filter/overview reads snappy.
"""

from __future__ import annotations

import datetime as dt
import decimal
import threading
import time
from typing import Any

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from . import config

_CACHE: dict[str, tuple[float, Any]] = {}
_CACHE_LOCK = threading.Lock()
_CACHE_TTL_SECONDS = 60.0


class _OAuthConnection(psycopg.Connection):
    """Connection subclass that injects a fresh OAuth token as the password."""

    @classmethod
    def connect(cls, conninfo: str = "", **kwargs):
        kwargs["password"] = config.get_db_token()
        conn = super().connect(conninfo, **kwargs)
        # Disable client-side prepared statements. The Gold tables are recreated
        # by the sync pipeline, which invalidates cached plans on pooled
        # connections ("cached plan must not change result type"). No prepared
        # plans -> no stale plans.
        conn.prepare_threshold = None
        return conn


def _conninfo() -> str:
    return (
        f"host={config.PGHOST} port={config.PGPORT} dbname={config.PGDATABASE} "
        f"user={config.get_pguser()} sslmode={config.PGSSLMODE}"
    )


# Deferred open — opened in the FastAPI lifespan so startup fails fast if the DB
# is unreachable rather than hanging requests.
pool = ConnectionPool(
    conninfo=_conninfo(),
    connection_class=_OAuthConnection,
    min_size=1,
    max_size=10,
    max_lifetime=2700,  # 45 min — recycle before the 1-hour token expires
    open=False,
    kwargs={"options": f"-c search_path={config.GOLD_SCHEMA},public"},
)


def _jsonify(value: Any) -> Any:
    """Make warehouse/Postgres values JSON-serializable."""
    if isinstance(value, (dt.date, dt.datetime)):
        return value.isoformat()
    if isinstance(value, decimal.Decimal):
        return float(value)
    if isinstance(value, (list, tuple)):
        return [_jsonify(v) for v in value]
    return value


def query(statement: str, parameters: dict | None = None) -> list[dict]:
    """Run a SQL statement, returning rows as JSON-safe dicts."""
    with pool.connection() as conn:
        with conn.cursor(row_factory=dict_row) as cur:
            cur.execute(statement, parameters or {})
            rows = cur.fetchall()
    return [{k: _jsonify(v) for k, v in row.items()} for row in rows]


def execute(statement: str, parameters: dict | None = None) -> list[dict]:
    """Run a write (INSERT/UPDATE/DELETE ... RETURNING) and return any rows."""
    with pool.connection() as conn:
        with conn.cursor(row_factory=dict_row) as cur:
            cur.execute(statement, parameters or {})
            rows = cur.fetchall() if cur.description else []
        conn.commit()
    return [{k: _jsonify(v) for k, v in row.items()} for row in rows]


# App-state schema (writable, owned by the connecting principal — the app SP in
# production). Gold stays read-only; app-generated state lives here. Statements
# run individually with autocommit so an already-granted GRANT (run by whoever
# created the schema first) is a harmless no-op rather than a fatal error.
_BOOTSTRAP_STATEMENTS = [
    "create schema if not exists app",
    """create table if not exists app.saved_opportunities (
        opportunity_id text not null,
        user_email     text not null,
        status         text not null default 'new',
        note           text,
        created_at     timestamptz default now(),
        updated_at     timestamptz default now(),
        primary key (user_email, opportunity_id)
    )""",
    """create table if not exists app.saved_drafts (
        id             bigint generated by default as identity primary key,
        opportunity_id text not null,
        user_email     text not null,
        variant        text,
        channel        text,
        language       text,
        content        text not null,
        created_at     timestamptz default now()
    )""",
    # Daily signal-count snapshots, so the header can show a real "since
    # yesterday" delta (the Gold cards have no per-row ingestion timestamp).
    """create table if not exists app.signal_count_history (
        day          date primary key,
        total        int not null,
        recorded_at  timestamptz default now()
    )""",
    "grant usage, create on schema app to public",
    "grant select, insert, update, delete on all tables in schema app to public",
    "grant usage, select on all sequences in schema app to public",
    "alter default privileges in schema app grant select, insert, update, delete on tables to public",
]


def bootstrap_app_state() -> None:
    """Create the app-state schema/tables if missing. Non-fatal on grant races."""
    errors: list[str] = []
    with pool.connection() as conn:
        conn.autocommit = True
        for stmt in _BOOTSTRAP_STATEMENTS:
            try:
                conn.execute(stmt)
            except Exception as exc:  # e.g. GRANT already done by another owner
                errors.append(f"{stmt.split('(')[0].strip()[:40]}: {exc}")
    if errors:
        print("[bootstrap_app_state] non-fatal:", errors)


def cached_query(cache_key: str, statement: str, parameters: dict | None = None) -> list[dict]:
    """`query` with a short TTL cache keyed by `cache_key`."""
    now = time.monotonic()
    with _CACHE_LOCK:
        hit = _CACHE.get(cache_key)
        if hit and now - hit[0] < _CACHE_TTL_SECONDS:
            return hit[1]
    result = query(statement, parameters)
    with _CACHE_LOCK:
        _CACHE[cache_key] = (now, result)
    return result
